/**
 * tools/build_web_lib.mjs — package the library for the browser.
 *
 * The web calculator and the landing page run every statistic in the
 * browser with the shipped library itself. Browsers loading the page from
 * the file system cannot use ES modules, and a Web Worker needs a classic
 * script to importScripts, so this tool concatenates the source modules
 * into one classic script exposing `PRERELATION` on the global object.
 *
 * The transformation is purely mechanical — strip `export ` keywords,
 * drop `import` statements (module order supplies the names), and replace
 * core's late-bound prng namespace import with a literal object. The
 * engine sources in src/ are read, never written. `test/web_calc.test.mjs`
 * verifies both freshness (rebuilding reproduces the committed bundle
 * byte for byte) and parity (the bundle's outputs equal the module
 * outputs exactly).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

export function buildBundleSource() {
  const strip = (name) => {
    let code = readFileSync(join(root, "src", name), "utf8");
    // The late-bound namespace import in core.mjs: the bundle places
    // prng.mjs first, so a literal object at the same position suffices.
    code = code.replace(
      /^import \* as _prng from "\.\/prng\.mjs";$/m,
      "const _prng = { sfc32, permutationStream };"
    );
    // Remaining import statements: the names are already in scope.
    code = code.replace(/^import[^\n]*\n/gm, "");
    // export const / export function -> plain declarations.
    code = code.replace(/^export\s+/gm, "");
    return code.trimEnd();
  };

  const parts = [strip("prng.mjs"), strip("core.mjs"), strip("scan.mjs")];

  return [
    "/* Generated by tools/build_web_lib.mjs from src/ — DO NOT EDIT.",
    " * Regenerate with: npm run build:web",
    " * The ES modules in src/ are the source of truth; this classic-script",
    " * bundle exists so the demo page and its Web Worker can run the same",
    " * library without a build system or a server. */",
    "(function (root) {",
    '"use strict";',
    "",
    parts.join("\n\n"),
    "",
    "root.PRERELATION = {",
    "  DELTA: DELTA,",
    "  TOP_Q: TOP_Q,",
    "  MIN_INTERIOR: MIN_INTERIOR,",
    "  DENSE_MAX_N: DENSE_MAX_N,",
    "  prereqIndex: prereqIndex,",
    "  direction: direction,",
    "  permPvalue: permPvalue,",
    "  scan: scan,",
    "  bhFdr: bhFdr,",
    "  findCycles: findCycles,",
    "  transitiveReduction: transitiveReduction,",
    "  condense: condense,",
    "  sfc32: sfc32,",
    "  permutationStream: permutationStream,",
    "};",
    '})(typeof self !== "undefined" ? self : globalThis);',
    "",
  ].join("\n");
}

const invokedDirectly =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) {
  const out = join(root, "web", "prerelation.browser.js");
  writeFileSync(out, buildBundleSource());
  console.log(`wrote ${out}`);
}
