/* Generated by tools/build_web_lib.mjs from src/ — DO NOT EDIT.
 * Regenerate with: npm run build:web
 * The ES modules in src/ are the source of truth; this classic-script
 * bundle exists so the demo page and its Web Worker can run the same
 * library without a build system or a server. */
(function (root) {
"use strict";

/**
 * prerelation-js/prng — deterministic seeded pseudo-random permutations.
 *
 * Production path for `permPvalue` and `scan` when no permutation-index
 * matrix is injected. The generator is sfc32 seeded through splitmix32,
 * using 32-bit integer arithmetic only, so the stream is identical on
 * every JavaScript engine and platform.
 *
 * This stream is deliberately NOT numpy-compatible. Cross-implementation
 * p-value parity with the Python reference package is defined only through
 * injected permutation-index matrices (see `tests/golden/` in the Python
 * repository); the internal stream exists so that production runs are
 * reproducible from a recorded seed.
 */

function splitmix32(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x9e3779b9) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 16), 0x21f0aaad);
    t = Math.imul(t ^ (t >>> 15), 0x735a2d97);
    return (t ^ (t >>> 15)) >>> 0;
  };
}

/** sfc32 generator returning uint32 values. */
function sfc32(seed) {
  const sm = splitmix32(seed);
  let a = sm();
  let b = sm();
  let c = sm();
  let d = sm();
  function next() {
    const t = (a + b + d) >>> 0;
    d = (d + 1) >>> 0;
    a = b ^ (b >>> 9);
    b = (c + (c << 3)) >>> 0;
    c = ((c << 21) | (c >>> 11)) >>> 0;
    c = (c + t) >>> 0;
    return t;
  }
  for (let i = 0; i < 12; i++) next(); // warm-up
  return next;
}

/**
 * Unbiased bounded integer in [0, bound) by threshold rejection.
 * @param {() => number} next - uint32 source.
 * @param {number} bound - exclusive upper bound, 1 <= bound <= 2**32.
 */
function boundedInt(next, bound) {
  if (bound <= 0) throw new RangeError("bound must be positive");
  const threshold = (0x100000000 % bound) >>> 0; // 2**32 mod bound
  for (;;) {
    const r = next();
    if (r >= threshold) return r % bound;
  }
}

/**
 * Stream of permutations of 0..n-1 from one seeded generator, drawn by
 * Fisher-Yates. Each call to the returned function yields the next
 * permutation in the stream (a fresh Int32Array).
 *
 * @param {number} seed
 * @param {number} n
 * @returns {() => Int32Array}
 */
function permutationStream(seed, n) {
  const next = sfc32(seed);
  return function () {
    const p = new Int32Array(n);
    for (let i = 0; i < n; i++) p[i] = i;
    for (let i = n - 1; i > 0; i--) {
      const j = boundedInt(next, i + 1);
      const tmp = p[i];
      p[i] = p[j];
      p[j] = tmp;
    }
    return p;
  };
}

/**
 * prerelation-js/core — the prerelation coefficient and its direction
 * statistic, ported from the Python reference implementation
 * (prerelation 0.2.0, https://github.com/JaehwaFChoi/prerelation).
 *
 * The coefficient
 * ---------------
 * For a pair of traits reported on a common anchored scale [0, 1],
 *
 *     Pi(X -> Y) = A1 * A2
 *
 *     A1 = max(0, 1 - v / v0)   emptiness of the corner {Y > X}, measured
 *                               against the independence baseline v0
 *     A2 = q * ell              conditional freedom, censoring-aware
 *
 *     Delta = Pi(X -> Y) - Pi(Y - X).
 *
 * Anchored scales are an interpretability requirement, not a claim about
 * the measurement precision of any scoring model: on an unanchored scale
 * Pi carries no prerequisite interpretation.
 *
 * Correctness standard
 * --------------------
 * The Python package's `tests/oracle/prereq_index_v2.py` is the permanent
 * oracle; this module transcribes every branch of the definition literally
 * and the golden-vector tests pin the outputs to the published fixtures at
 * 1e-12 (exact for permutation p-values). The following are part of the
 * *definition*, not implementation detail:
 *
 * - the independence baseline is a V-statistic — the double sum runs over
 *   all n**2 ordered pairs, the diagonal i = j included;
 * - `v0 <= 1e-9` forces `A1 = 0`;
 * - fewer than `max(10, 0.05 n)` interior points forces `q = 0`;
 * - an empty top-x stratum forces `p1_top = 1` (hence `ell = 0`);
 * - the ratio is clipped to [0, 1] and its denominator floored at 1e-9.
 *
 * The defaults `delta = 0.05`, `TOP_Q = 0.8` and
 * `MIN_INTERIOR = max(10, 0.05 n)` are fixed conventions of the
 * definition. Do not expose or change them.
 */

const DELTA = 0.05; // ceiling band width
const TOP_Q = 0.8; // top-x quantile for the legitimacy check
const MIN_INTERIOR = 10; // minimum interior points before freedom is credited

const EPS_DEN = 1e-9; // floor of the ratio denominator
const EPS_V0 = 1e-9; // guard on the independence baseline

// Above this sample size the baseline is accumulated by sorting instead of
// forming the n x n double sum. The two paths agree to floating-point
// rounding (they differ only in summation order); below the threshold the
// dense expression of the oracle is used verbatim. Mirrors the Python
// reference constant.
const DENSE_MAX_N = 3000;

/** Neumaier (improved Kahan) compensated sum of a numeric array. */
function compensatedSum(arr) {
  let sum = 0.0;
  let c = 0.0;
  for (let i = 0; i < arr.length; i++) {
    const x = arr[i];
    const t = sum + x;
    if (Math.abs(sum) >= Math.abs(x)) {
      c += sum - t + x;
    } else {
      c += x - t + sum;
    }
    sum = t;
  }
  return sum + c;
}

function asPair(x, y) {
  if (!Array.isArray(x) && !ArrayBuffer.isView(x)) {
    throw new TypeError("x must be an array of numbers");
  }
  if (!Array.isArray(y) && !ArrayBuffer.isView(y)) {
    throw new TypeError("y must be an array of numbers");
  }
  if (x.length !== y.length) {
    throw new RangeError(
      `x and y must have equal length, got ${x.length} and ${y.length}`
    );
  }
  if (x.length === 0) {
    throw new RangeError("x and y must be non-empty");
  }
  return [Float64Array.from(x), Float64Array.from(y)];
}

/**
 * Independence baseline v0 = mean over all n**2 ordered pairs of
 * (y_j - x_i)_+. The diagonal is included: a V-statistic, not a
 * U-statistic.
 */
function baselineMean(x, y, denseMaxN) {
  const n = x.length;
  if (n <= denseMaxN) {
    // Literal double sum of the oracle, with compensated accumulation.
    let sum = 0.0;
    let c = 0.0;
    for (let i = 0; i < n; i++) {
      const xi = x[i];
      for (let j = 0; j < n; j++) {
        const d = y[j] - xi;
        const term = d > 0.0 ? d : 0.0;
        const t = sum + term;
        if (Math.abs(sum) >= Math.abs(term)) {
          c += sum - t + term;
        } else {
          c += term - t + sum;
        }
        sum = t;
      }
    }
    return (sum + c) / (n * n);
  }

  // Sort-and-accumulate: for each x_i, sum_j (y_j - x_i)_+ equals the sum
  // of the y above x_i minus x_i times how many there are. O(n log n).
  const ys = Float64Array.from(y).sort();
  const tail = new Float64Array(n + 1); // tail[k] = sum(ys[k:])
  tail[n] = 0.0;
  for (let k = n - 1; k >= 0; k--) tail[k] = tail[k + 1] + ys[k];
  const inner = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    // count of y_j <= x_i  (searchsorted side="right")
    let lo = 0;
    let hi = n;
    const xi = x[i];
    while (lo < hi) {
      const mid = (lo + hi) >>> 1;
      if (ys[mid] <= xi) lo = mid + 1;
      else hi = mid;
    }
    inner[i] = tail[lo] - xi * (n - lo);
  }
  return compensatedSum(inner) / n / n;
}

/**
 * Quantile with linear interpolation, replicating numpy's method="linear"
 * including its half-way switch between the two lerp formulas.
 */
function quantileLinear(sorted, q) {
  const n = sorted.length;
  if (n === 1) return sorted[0];
  const pos = q * (n - 1);
  const lo = Math.floor(pos);
  const hi = lo + 1 >= n ? n - 1 : lo + 1;
  const t = pos - lo;
  const a = sorted[lo];
  const b = sorted[hi];
  const diff = b - a;
  let lerp = a + diff * t;
  if (t >= 0.5) lerp = b - diff * (1 - t);
  return lerp;
}

/**
 * Prerelation coefficient of the ordered pair (x -> y).
 *
 * @param {ArrayLike<number>} x - candidate prerequisite, values in [0, 1]
 *   on a common anchored scale.
 * @param {ArrayLike<number>} y - candidate dependent trait, same scale.
 * @param {object} [opts]
 * @param {number} [opts.delta=0.05] - ceiling band width (fixed convention).
 * @param {number} [opts.denseMaxN=3000] - sample size up to which the
 *   independence baseline is formed as the literal double sum.
 * @returns {{PI: number, A1: number, A2: number, q: number, ell: number}}
 *   Keys mirror the Python reference return interface exactly.
 *
 * The statistic is deliberately not invariant to monotone rescaling of
 * either axis, and it is not symmetric: `prereqIndex(y, x)` answers a
 * different question.
 */
function prereqIndex(x, y, opts = {}) {
  const delta = opts.delta ?? DELTA;
  const denseMaxN = opts.denseMaxN ?? DENSE_MAX_N;
  const [xa, ya] = asPair(x, y);
  const n = xa.length;

  // A1: corner emptiness relative to the independence baseline.
  const corner = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    const d = ya[i] - xa[i];
    corner[i] = d > 0.0 ? d : 0.0;
  }
  const v = compensatedSum(corner) / n;
  const v0 = baselineMean(xa, ya, denseMaxN);
  const a1 = v0 > EPS_V0 ? Math.max(0.0, 1.0 - v / v0) : 0.0;

  // A2: conditional freedom with a censoring-aware benchmark.
  const u = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    const den = xa[i] > EPS_DEN ? xa[i] : EPS_DEN;
    let r = ya[i] / den;
    if (r < 0.0) r = 0.0;
    else if (r > 1.0) r = 1.0;
    u[i] = r;
  }
  const ceilCut = 1.0 - delta;
  const interior = [];
  const ceilMask = new Uint8Array(n);
  for (let i = 0; i < n; i++) {
    if (u[i] >= ceilCut) ceilMask[i] = 1;
    else interior.push(u[i]);
  }

  let q;
  if (interior.length < Math.max(MIN_INTERIOR, 0.05 * n)) {
    q = 0.0;
  } else {
    const t = Float64Array.from(interior, (w) => w / ceilCut).sort();
    let maxDev = 0.0;
    const m = t.length;
    for (let i = 0; i < m; i++) {
      const dev = Math.abs((i + 1) / m - t[i]);
      if (dev > maxDev) maxDev = dev;
    }
    q = 1.0 - maxDev;
  }

  const xSorted = Float64Array.from(xa).sort();
  const thr = quantileLinear(xSorted, TOP_Q);
  let nTop = 0;
  let nTopCeil = 0;
  for (let i = 0; i < n; i++) {
    if (xa[i] >= thr) {
      nTop += 1;
      if (ceilMask[i]) nTopCeil += 1;
    }
  }
  const p1Top = nTop > 0 ? nTopCeil / nTop : 1.0;
  const ell = 1.0 - Math.max(0.0, p1Top - delta) / (1.0 - delta);

  const a2 = q * ell;
  return { PI: a1 * a2, A1: a1, A2: a2, q, ell };
}

/**
 * Directional contrast of the pair.
 *
 * @returns {{delta: number, forward: number, reverse: number}} where
 *   `delta = forward - reverse`, `forward = Pi(x -> y)` and
 *   `reverse = Pi(y -> x)`.
 */
function direction(x, y, opts = {}) {
  const forward = prereqIndex(x, y, opts).PI;
  const reverse = prereqIndex(y, x, opts).PI;
  return { delta: forward - reverse, forward, reverse };
}

/**
 * Permutation test of independence for the forward statistic.
 *
 * Under the null of independence the joint law of the sample is invariant
 * under permutations of the y-labels; the Monte-Carlo version inherits
 * validity because the observed configuration is counted in the reference
 * set (the add-one rule): p = (1 + #{r: PI_r >= PI_obs}) / (nPerm + 1).
 *
 * Two sources of permutations are supported:
 *
 * - `opts.indices`: an injected permutation-index matrix — an array of
 *   `nPerm` rows, each a permutation of `0..n-1`. This is the parity path:
 *   with the committed index matrices from the Python reference package's
 *   `tests/golden/`, the p-value must equal the published expected value
 *   exactly (it is count-based).
 * - `opts.seed` with the internal generator (see prng.mjs) for production
 *   use. The internal generator is deterministic and seeded but is NOT the
 *   same stream as numpy's; cross-implementation p-value parity is only
 *   defined through injected indices.
 *
 * @returns {{observed: number, pValue: number}}
 */
function permPvalue(x, y, opts = {}) {
  const delta = opts.delta ?? DELTA;
  const denseMaxN = opts.denseMaxN ?? DENSE_MAX_N;
  const [xa, ya] = asPair(x, y);
  const obs = prereqIndex(xa, ya, { delta, denseMaxN }).PI;

  let cnt = 0;
  let nPerm;
  if (opts.indices != null) {
    const indices = opts.indices;
    nPerm = indices.length;
    const yPerm = new Float64Array(ya.length);
    for (let r = 0; r < nPerm; r++) {
      const row = indices[r];
      if (row.length !== ya.length) {
        throw new RangeError(
          `indices row ${r} has length ${row.length}, expected ${ya.length}`
        );
      }
      for (let i = 0; i < ya.length; i++) yPerm[i] = ya[row[i]];
      if (prereqIndex(xa, yPerm, { delta, denseMaxN }).PI >= obs) cnt += 1;
    }
  } else {
    nPerm = opts.nPerm ?? 1000;
    const seed = opts.seed ?? 0;
    // Imported lazily to keep core free of a hard dependency direction.
    const { permutationStream } = _prngModule();
    const nextPerm = permutationStream(seed, ya.length);
    const yPerm = new Float64Array(ya.length);
    for (let r = 0; r < nPerm; r++) {
      const row = nextPerm();
      for (let i = 0; i < ya.length; i++) yPerm[i] = ya[row[i]];
      if (prereqIndex(xa, yPerm, { delta, denseMaxN }).PI >= obs) cnt += 1;
    }
  }
  return { observed: obs, pValue: (cnt + 1) / (nPerm + 1) };
}

// Late-bound import so core.mjs stays loadable in isolation for the pure
// closed-form functions even if prng.mjs is absent (it never is in the
// shipped package; this only defers module resolution).
const _prng = { sfc32, permutationStream };
function _prngModule() {
  return _prng;
}

/**
 * prerelation-js/scan — pairwise screening of a whole attribute set.
 *
 * `scan` takes an (nPersons x nAttributes) matrix of trait values on a
 * common anchored scale and returns
 *
 * - a tidy record per ordered pair with Pi, the reverse Pi, Delta and a
 *   permutation p-value;
 * - the edge set surviving Benjamini-Hochberg control of the false
 *   discovery rate;
 * - a cycle report;
 * - the transitive reduction of the edge set when it is acyclic; and
 * - the equivalence-class condensation with its quotient order (see
 *   `condense`), which is always defined even when the raw edge set has
 *   cycles — the Hasse diagram of the scan is drawn on the quotient.
 *
 * What the scan recovers is a **dominance preorder** over the attributes —
 * the ordering induced by which attributes act as ceilings on which
 * others — not a direct-prerequisite DAG. Indirect dominance produces
 * edges of its own (removed only along chains by the transitive
 * reduction), and siblings that share a common ceiling can be linked to
 * each other even though neither is a prerequisite for the other. A
 * disagreement between the recovered order and an expert-specified
 * prerequisite graph is therefore a difference between two concepts, not
 * by itself an error in either. Mutually dominating attributes (directed
 * cycles) are expected behavior of a pairwise index and are read as
 * equivalence classes of the preorder.
 */


/** Benjamini-Hochberg adjusted p-values (step-up, monotonised). */
function bhFdr(pvalues) {
  const p = Float64Array.from(pvalues);
  const m = p.length;
  if (m === 0) return [];
  const order = Array.from(p.keys()).sort((i, j) => p[i] - p[j] || i - j);
  const ranked = new Float64Array(m);
  for (let r = 0; r < m; r++) ranked[r] = (p[order[r]] * m) / (r + 1);
  for (let r = m - 2; r >= 0; r--) {
    if (ranked[r + 1] < ranked[r]) ranked[r] = ranked[r + 1];
  }
  const out = new Array(m);
  for (let r = 0; r < m; r++) {
    out[order[r]] = Math.min(1.0, Math.max(0.0, ranked[r]));
  }
  return out;
}

/** Return the directed cycles found by depth-first search (may be empty). */
function findCycles(nodes, edges) {
  const adj = new Map(nodes.map((u) => [u, []]));
  for (const [u, v] of edges) adj.get(u).push(v);
  const colour = new Map(nodes.map((u) => [u, 0])); // 0 white, 1 grey, 2 black
  const stack = [];
  const cycles = [];

  function visit(u) {
    colour.set(u, 1);
    stack.push(u);
    for (const v of adj.get(u)) {
      if (colour.get(v) === 0) visit(v);
      else if (colour.get(v) === 1) {
        cycles.push(stack.slice(stack.indexOf(v)).concat([v]));
      }
    }
    stack.pop();
    colour.set(u, 2);
  }

  for (const u of nodes) if (colour.get(u) === 0) visit(u);
  return cycles;
}

function reachableSkipping(adj, src, dst, skipU, skipV) {
  const stack = [src];
  const seen = new Set([src]);
  while (stack.length > 0) {
    const u = stack.pop();
    for (const v of adj.get(u)) {
      if (u === skipU && v === skipV) continue;
      if (v === dst) return true;
      if (!seen.has(v)) {
        seen.add(v);
        stack.push(v);
      }
    }
  }
  return false;
}

/**
 * Transitive reduction of a directed acyclic graph. An edge is dropped
 * when the same ordering is already implied by a path of length two or
 * more. Throws if the graph has a cycle, where the reduction is not
 * unique.
 */
function transitiveReduction(nodes, edges) {
  const cycles = findCycles(nodes, edges);
  if (cycles.length > 0) {
    throw new Error(
      "transitive reduction is only defined for acyclic graphs; " +
        `found cycle ${JSON.stringify(cycles[0])}`
    );
  }
  const adj = new Map(nodes.map((u) => [u, new Set()]));
  for (const [u, v] of edges) adj.get(u).add(v);
  const kept = [];
  for (const [u, v] of edges) {
    if (!reachableSkipping(adj, u, v, u, v)) kept.push([u, v]);
  }
  return kept;
}

/**
 * Equivalence-class condensation of a directed graph and its quotient
 * order.
 *
 * Attributes that dominate each other through a directed cycle are read as
 * one equivalence class of the dominance preorder. The condensation
 * contracts every strongly connected component (Tarjan) to a single node;
 * the resulting quotient graph is acyclic by construction, so the quotient
 * order always has a transitive reduction — the Hasse edge set on which
 * the diagram of a scan is drawn.
 *
 * @param {string[]} nodes
 * @param {Array<[string, string]>} edges
 * @returns {{
 *   classes: string[][],           // each class sorted in `nodes` order;
 *                                  // classes sorted by first member
 *   classOf: Map<string, number>,  // node -> index into classes
 *   quotientEdges: Array<[number, number]>,  // deduplicated, between
 *                                            // distinct classes
 *   hasseEdges: Array<[number, number]>      // transitive reduction of
 *                                            // the quotient DAG
 * }}
 */
function condense(nodes, edges) {
  const adj = new Map(nodes.map((u) => [u, []]));
  for (const [u, v] of edges) adj.get(u).push(v);

  // Tarjan's strongly connected components (iterative).
  const index = new Map();
  const low = new Map();
  const onStack = new Set();
  const tarjanStack = [];
  const components = [];
  let counter = 0;

  for (const start of nodes) {
    if (index.has(start)) continue;
    const work = [[start, 0]];
    while (work.length > 0) {
      const frame = work[work.length - 1];
      const u = frame[0];
      if (frame[1] === 0) {
        index.set(u, counter);
        low.set(u, counter);
        counter += 1;
        tarjanStack.push(u);
        onStack.add(u);
      }
      const neighbours = adj.get(u);
      let advanced = false;
      while (frame[1] < neighbours.length) {
        const v = neighbours[frame[1]];
        frame[1] += 1;
        if (!index.has(v)) {
          work.push([v, 0]);
          advanced = true;
          break;
        } else if (onStack.has(v)) {
          low.set(u, Math.min(low.get(u), index.get(v)));
        }
      }
      if (advanced) continue;
      if (low.get(u) === index.get(u)) {
        const comp = [];
        for (;;) {
          const w = tarjanStack.pop();
          onStack.delete(w);
          comp.push(w);
          if (w === u) break;
        }
        components.push(comp);
      }
      work.pop();
      if (work.length > 0) {
        const parent = work[work.length - 1][0];
        low.set(parent, Math.min(low.get(parent), low.get(u)));
      }
    }
  }

  const nodeOrder = new Map(nodes.map((u, i) => [u, i]));
  const classes = components
    .map((comp) => comp.slice().sort((a, b) => nodeOrder.get(a) - nodeOrder.get(b)))
    .sort((a, b) => nodeOrder.get(a[0]) - nodeOrder.get(b[0]));
  const classOf = new Map();
  classes.forEach((comp, ci) => comp.forEach((u) => classOf.set(u, ci)));

  const seen = new Set();
  const quotientEdges = [];
  for (const [u, v] of edges) {
    const cu = classOf.get(u);
    const cv = classOf.get(v);
    if (cu === cv) continue;
    const key = `${cu}->${cv}`;
    if (!seen.has(key)) {
      seen.add(key);
      quotientEdges.push([cu, cv]);
    }
  }

  const classIds = classes.map((_, ci) => ci);
  const hasseEdges = transitiveReduction(classIds, quotientEdges);
  return { classes, classOf, quotientEdges, hasseEdges };
}

/**
 * Screen every ordered pair of attributes for ceiling dominance.
 *
 * The edge set (and its transitive reduction) is read as a *dominance
 * preorder* over the attributes, not as a recovered direct-prerequisite
 * DAG; see the module docstring for what separates the two.
 *
 * **Design floor on permutation replicates.** With `k` attributes there
 * are `K = k (k - 1)` ordered pairs, and the smallest attainable
 * permutation p-value is `1 / (nPerm + 1)`. For any pair to survive
 * Benjamini-Hochberg control at level `alpha` the replicate count must
 * satisfy `nPerm >= K / alpha - 1` (e.g. `K = 6`, `alpha = 0.05` requires
 * `nPerm >= 119`; `K = 56` requires `nPerm >= 1119`). Below the floor the
 * scan cannot return any edge, regardless of the data.
 *
 * @param {number[][]} thetaMatrix - rows are persons, columns attributes;
 *   values on a common anchored scale.
 * @param {object} [opts]
 * @param {number} [opts.alpha=0.05] - target FDR for BH, applied jointly
 *   to all ordered pairs.
 * @param {string[]} [opts.names] - attribute labels; defaults to A1, A2...
 * @param {number} [opts.nPerm=999] - permutation replicates per ordered
 *   pair. With the internal generator each pair gets its own stream,
 *   seeded as `seed + pairPosition` (pairPosition enumerates ordered
 *   pairs row-major, diagonal skipped), so results are reproducible and
 *   independent of the order of evaluation.
 * @param {number} [opts.seed=0]
 * @param {number} [opts.delta=0.05]
 * @param {number} [opts.minPi=0] - additional floor on Pi for an edge to
 *   be kept; 0 by default, since significance is the primary rule.
 * @param {boolean} [opts.requirePositiveDelta=true] - keep an edge only
 *   when the forward direction dominates the reverse.
 * @param {(pairPosition: number, n: number) => ArrayLike<ArrayLike<number>>}
 *   [opts.indicesProvider] - parity hook: when given, permutations for the
 *   pair at `pairPosition` are taken from the returned index matrix
 *   instead of the internal generator (`nPerm` is then that matrix's row
 *   count).
 * @param {(done: number, total: number) => void} [opts.onProgress]
 * @returns {{
 *   records: object[], edges: Array<[string, string]>,
 *   reducedEdges: Array<[string, string]> | null,
 *   cycles: string[][],
 *   equivalenceClasses: string[][],
 *   quotient: {classes: string[][], quotientEdges: Array<[number, number]>,
 *              hasseEdges: Array<[number, number]>},
 *   names: string[], alpha: number, meta: object
 * }}
 */
function scan(thetaMatrix, opts = {}) {
  const alpha = opts.alpha ?? 0.05;
  const nPermOpt = opts.nPerm ?? 999;
  const seed = opts.seed ?? 0;
  const delta = opts.delta ?? DELTA;
  const minPi = opts.minPi ?? 0.0;
  const requirePositiveDelta = opts.requirePositiveDelta ?? true;

  const theta = thetaMatrix.map((row) => Float64Array.from(row));
  if (theta.length === 0 || theta[0].length < 2) {
    throw new RangeError("need at least two attributes and one person to scan");
  }
  const n = theta.length;
  const k = theta[0].length;
  for (const row of theta) {
    if (row.length !== k) {
      throw new RangeError("thetaMatrix rows must all have the same length");
    }
  }
  let names = opts.names ?? Array.from({ length: k }, (_, j) => `A${j + 1}`);
  names = names.slice();
  if (names.length !== k) {
    throw new RangeError("names must have one entry per attribute");
  }

  const col = (j) => {
    const out = new Float64Array(n);
    for (let i = 0; i < n; i++) out[i] = theta[i][j];
    return out;
  };
  const columns = Array.from({ length: k }, (_, j) => col(j));

  const piMatrix = Array.from({ length: k }, () => new Float64Array(k).fill(NaN));
  const compMatrix = Array.from({ length: k }, () => new Array(k).fill(null));
  for (let i = 0; i < k; i++) {
    for (let j = 0; j < k; j++) {
      if (i !== j) {
        const res = prereqIndex(columns[i], columns[j], { delta });
        piMatrix[i][j] = res.PI;
        compMatrix[i][j] = res;
      }
    }
  }

  const totalPairs = k * (k - 1);
  const records = [];
  let pairPosition = 0;
  for (let i = 0; i < k; i++) {
    for (let j = 0; j < k; j++) {
      if (i === j) continue;
      const x = columns[i];
      const y = columns[j];
      const res = compMatrix[i][j];
      const obs = res.PI;

      let cnt = 0;
      let nPerm;
      const yPerm = new Float64Array(n);
      if (opts.indicesProvider != null) {
        const indices = opts.indicesProvider(pairPosition, n);
        nPerm = indices.length;
        for (let r = 0; r < nPerm; r++) {
          const row = indices[r];
          for (let t = 0; t < n; t++) yPerm[t] = y[row[t]];
          if (prereqIndex(x, yPerm, { delta }).PI >= obs) cnt += 1;
        }
      } else {
        nPerm = nPermOpt;
        const nextPerm = permutationStream(seed + pairPosition, n);
        for (let r = 0; r < nPerm; r++) {
          const row = nextPerm();
          for (let t = 0; t < n; t++) yPerm[t] = y[row[t]];
          if (prereqIndex(x, yPerm, { delta }).PI >= obs) cnt += 1;
        }
      }
      const pValue = (cnt + 1) / (nPerm + 1);

      records.push({
        source: names[i],
        target: names[j],
        pi: obs,
        pi_reverse: piMatrix[j][i],
        delta: obs - piMatrix[j][i],
        A1: res.A1,
        A2: res.A2,
        q: res.q,
        ell: res.ell,
        p_value: pValue,
        n,
        n_perm: nPerm,
      });
      pairPosition += 1;
      if (opts.onProgress) opts.onProgress(pairPosition, totalPairs);
    }
  }

  const pAdj = bhFdr(records.map((r) => r.p_value));
  const edges = [];
  records.forEach((rec, idx) => {
    rec.p_adj = pAdj[idx];
    let keep = pAdj[idx] <= alpha && rec.pi >= minPi;
    if (requirePositiveDelta) keep = keep && rec.delta > 0;
    rec.edge = keep;
    if (keep) edges.push([rec.source, rec.target]);
  });

  const cycles = findCycles(names, edges);
  const reducedEdges = cycles.length > 0 ? null : transitiveReduction(names, edges);
  const quotient = condense(names, edges);

  return {
    records,
    edges,
    reducedEdges,
    cycles,
    equivalenceClasses: quotient.classes,
    quotient,
    names,
    alpha,
    meta: { n, nPerm: nPermOpt, seed, delta },
  };
}

root.PRERELATION = {
  DELTA: DELTA,
  TOP_Q: TOP_Q,
  MIN_INTERIOR: MIN_INTERIOR,
  DENSE_MAX_N: DENSE_MAX_N,
  prereqIndex: prereqIndex,
  direction: direction,
  permPvalue: permPvalue,
  scan: scan,
  bhFdr: bhFdr,
  findCycles: findCycles,
  transitiveReduction: transitiveReduction,
  condense: condense,
  sfc32: sfc32,
  permutationStream: permutationStream,
};
})(typeof self !== "undefined" ? self : globalThis);
